[project]
name = "pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vlado Ivanov Vodenicharov", email = "134718051+VladoVodenicharov@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.5",
    "pgcli>=4.7.0",
    "psycopg2-binary>=2.9.13",
    "psycopg[binary,pool]>=3.3.6",
    "pyarrow>=25.0.1",
    "sqlalchemy>=2.0.54",
    "tqdm>=4.70.1",
    "click"
]

[project.scripts]
pipeline = "pipeline:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
